// Generated by CoffeeScript 1.4.0
var $LS4D, LineSegment4D;

$LS4D = function(e1, e2) {
  return new LineSegment4D(e1, e2);
};

LineSegment4D = (function() {

  function LineSegment4D(e1, e2) {
    this.e1 = e1;
    this.e2 = e2;
    this.p = this.e1;
    this.v = this.e2.subtract(this.e1);
  }

  return LineSegment4D;

})();
