// Generated by CoffeeScript 1.4.0
var $P4D, Polygon4D;

$P4D = function(p) {
  return new Polygon4D(p);
};

Polygon4D = (function() {

  function Polygon4D(points) {
    this.points = points;
  }

  return Polygon4D;

})();
