// Generated by CoffeeScript 1.4.0
var zip, zipWith;

zip = function(xs, ys) {
  var rest;
  if (!(xs.length && ys.length)) {
    return [];
  }
  rest = zip(xs.slice(1), ys.slice(1));
  rest.unshift({
    _1: xs[0],
    _2: ys[0]
  });
  return rest;
};

zipWith = function(xs, ys, fn) {
  return (zip(xs, ys)).map(function(x) {
    return fn(x._1, x._2);
  });
};
