{spawn} = require 'child_process'
{print} = require 'util'

src = ['coffee']

build = ->
    for name in src
        coffee = spawn 'coffee', ['-c', '-o', '.', name]
        coffee.stderr.on 'data', (data) ->
            process.stderr.write data.toString()
        coffee.stdout.on 'data', (data) ->
            print data.toString()
        coffee.on 'exit', (code) ->
            callback?() if code is 0

task 'build', 'build the javascript files for this project', ->
    build()

task 'watch', 'recompile coffeescript files whenever they are changed', ->
    console.log "Starting CoffeeScript compiler (watching for changes in /coffee folder)..."
    coffee = spawn 'coffee', ['-w', '-cb', '-o', '.', 'coffee']
    coffee.stderr.on 'data', (data) ->
        process.stderr.write data.toString()
    coffee.stdout.on 'data', (data) ->
        print data.toString()
